-- =====================================================================
-- BoxVault - PostgreSQL schema (tables, constraints and indexes)
-- =====================================================================
--
-- This file is executed automatically by the "postgres" container the first
-- time its data volume is created (docker-entrypoint-initdb.d), against the
-- database named by POSTGRES_DB. 02-seed-data.sql loads the data right after.
--
-- To install it by hand on an existing PostgreSQL server instead, create the
-- database and the role first and then run the two files against it:
--
--     CREATE ROLE boxvault LOGIN PASSWORD 'change-me';
--     CREATE DATABASE boxvault OWNER boxvault ENCODING 'UTF8' TEMPLATE template0;
--
--     psql -U boxvault -d boxvault -f 01-schema.sql
--     psql -U boxvault -d boxvault -f 02-seed-data.sql
--
-- The column names and types are the ones Hibernate maps the entities to
-- (Spring's snake_case naming strategy), so the application starts against
-- this schema without recreating anything. spring.jpa.hibernate.ddl-auto is
-- left at "update", which only ever ADDS what a new entity field needs and
-- never drops these indexes.
--
-- Money is numeric(10,2) (numeric(12,2) for the tax figures) and percentages
-- are numeric(7,4), so that 1/6 -> 16.6667 round-trips.
-- =====================================================================

-- Trigram matching for the client search (ClientRepository.searchClients uses
-- LOWER(col) LIKE '%query%', which no btree index can serve).
CREATE EXTENSION IF NOT EXISTS pg_trgm;


-- ---------------------------------------------------------------------
-- clients - tenants
-- ---------------------------------------------------------------------
CREATE TABLE clients (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name         VARCHAR(150) NOT NULL,
    email             VARCHAR(150) NOT NULL,
    phone             VARCHAR(50)  NOT NULL,
    document_id       VARCHAR(50),
    address           VARCHAR(255),
    emergency_contact VARCHAR(150),
    notes             TEXT,
    created_at        TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

-- findByEmail: exact lookup.
CREATE INDEX idx_clients_email ON clients (email);
-- The seeder and the tax reports match tenants by name; also serves ORDER BY.
CREATE INDEX idx_clients_full_name ON clients (full_name);
-- searchClients: case-insensitive substring search on the three columns.
CREATE INDEX idx_clients_full_name_trgm ON clients USING GIN (LOWER(full_name) gin_trgm_ops);
CREATE INDEX idx_clients_email_trgm     ON clients USING GIN (LOWER(email)     gin_trgm_ops);
CREATE INDEX idx_clients_phone_trgm     ON clients USING GIN (LOWER(phone)     gin_trgm_ops);


-- ---------------------------------------------------------------------
-- storage_units - trasteros, apartments and locales (a tree via parent_unit_id)
-- ---------------------------------------------------------------------
CREATE TABLE storage_units (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_number         VARCHAR(50)  NOT NULL,
    kind                VARCHAR(30),
    parent_unit_id      BIGINT,
    name                VARCHAR(100) NOT NULL,
    size_square_meters  DOUBLE PRECISION NOT NULL,
    dimensions          VARCHAR(50),
    location            VARCHAR(100),
    cadastral_reference VARCHAR(30),
    base_monthly_rate   NUMERIC(10,2) NOT NULL,
    status              VARCHAR(30)  NOT NULL,
    description         TEXT,
    created_at          TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_storage_units_unit_number UNIQUE (unit_number),
    CONSTRAINT fk_storage_units_parent FOREIGN KEY (parent_unit_id) REFERENCES storage_units (id)
);

-- findByStatus / countByStatus (dashboard occupancy).
CREATE INDEX idx_storage_units_status ON storage_units (status);
-- findByKind, findByKindAndStatus and findByKindIsNull (btree indexes NULLs too).
CREATE INDEX idx_storage_units_kind_status ON storage_units (kind, status);
-- findByParentId / countByParentId, and findByParentIsNull through the NULL entries.
CREATE INDEX idx_storage_units_parent ON storage_units (parent_unit_id);


-- ---------------------------------------------------------------------
-- rental_agreements - tenancies
-- ---------------------------------------------------------------------
CREATE TABLE rental_agreements (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agreement_number     VARCHAR(50) NOT NULL,
    storage_unit_id      BIGINT      NOT NULL,
    client_id            BIGINT      NOT NULL,
    co_client_id         BIGINT,
    start_date           DATE        NOT NULL,
    end_date             DATE,
    billing_day_of_month INTEGER     NOT NULL,
    monthly_rent         NUMERIC(10,2) NOT NULL,
    security_deposit     NUMERIC(10,2),
    deposit_paid         BOOLEAN,
    status               VARCHAR(30) NOT NULL,
    auto_renew           BOOLEAN,
    notes                TEXT,
    created_at           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_rental_agreements_number UNIQUE (agreement_number),
    CONSTRAINT fk_rental_agreements_unit      FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id),
    CONSTRAINT fk_rental_agreements_client    FOREIGN KEY (client_id)       REFERENCES clients (id),
    CONSTRAINT fk_rental_agreements_co_client FOREIGN KEY (co_client_id)    REFERENCES clients (id)
);

-- findByStorageUnitId and findByStorageUnitIdAndStatus (the current tenancy of a unit).
CREATE INDEX idx_rental_agreements_unit_status ON rental_agreements (storage_unit_id, status);
-- findByClientId / findByClientIdOrCoClientId: one index per tenant column.
CREATE INDEX idx_rental_agreements_client    ON rental_agreements (client_id);
CREATE INDEX idx_rental_agreements_co_client ON rental_agreements (co_client_id) WHERE co_client_id IS NOT NULL;
-- findAllActiveRentals / countByStatus / countDistinctActiveClients: the hot path
-- is always status = 'ACTIVE', so this index only carries those rows.
CREATE INDEX idx_rental_agreements_active ON rental_agreements (storage_unit_id, client_id)
    WHERE status = 'ACTIVE';
-- findByStatus for the other states.
CREATE INDEX idx_rental_agreements_status ON rental_agreements (status);


-- ---------------------------------------------------------------------
-- payments - one invoice per tenancy and billing month (the biggest table)
-- ---------------------------------------------------------------------
CREATE TABLE payments (
    id                    BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_agreement_id   BIGINT  NOT NULL,
    storage_unit_id       BIGINT  NOT NULL,
    client_id             BIGINT  NOT NULL,
    billing_period_month  INTEGER NOT NULL,
    billing_period_year   INTEGER NOT NULL,
    amount_due            NUMERIC(10,2) NOT NULL,
    amount_paid           NUMERIC(10,2),
    due_date              DATE    NOT NULL,
    payment_date          DATE,
    status                VARCHAR(30) NOT NULL,
    payment_method        VARCHAR(30),
    transaction_reference VARCHAR(100),
    notes                 TEXT,
    created_at            TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_agreement FOREIGN KEY (rental_agreement_id) REFERENCES rental_agreements (id),
    CONSTRAINT fk_payments_unit      FOREIGN KEY (storage_unit_id)     REFERENCES storage_units (id),
    CONSTRAINT fk_payments_client    FOREIGN KEY (client_id)           REFERENCES clients (id)
);

-- findByRentalAgreementIdAndBillingPeriodYearAndBillingPeriodMonth returns an
-- Optional: one invoice per tenancy and period. Unique, so generating the
-- invoices of a month twice can never duplicate a row; it also serves
-- findByRentalAgreementId through its leading column.
CREATE UNIQUE INDEX ux_payments_agreement_period
    ON payments (rental_agreement_id, billing_period_year, billing_period_month);

-- The revenue aggregates (month / quarter / year, paid and pending) all filter
-- by status and period and only sum the two amounts: an index-only scan.
CREATE INDEX idx_payments_status_period
    ON payments (status, billing_period_year, billing_period_month)
    INCLUDE (amount_paid, amount_due);
-- findByBillingPeriodYear[AndMonth[Between]], without a status filter.
CREATE INDEX idx_payments_period ON payments (billing_period_year, billing_period_month);
-- sumRevenueByStorageUnit / sumPaidRevenueForUnit group the paid rows by unit,
-- and the per-unit history lists every payment of a unit in period order.
CREATE INDEX idx_payments_unit_period
    ON payments (storage_unit_id, billing_period_year, billing_period_month)
    INCLUDE (status, amount_paid);
-- findByClientId.
CREATE INDEX idx_payments_client ON payments (client_id);
-- findByDueDateBetween.
CREATE INDEX idx_payments_due_date ON payments (due_date);
-- findOverduePayments / sumTotalOverdueAmount: due_date < today among the
-- unsettled rows only, which are a small fraction of a growing table.
CREATE INDEX idx_payments_pending_due_date ON payments (due_date)
    WHERE status IN ('PENDING', 'OVERDUE');


-- ---------------------------------------------------------------------
-- unit_price_history - how the monthly price of a unit evolved
-- ---------------------------------------------------------------------
CREATE TABLE unit_price_history (
    id              BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_unit_id BIGINT NOT NULL,
    monthly_price   NUMERIC(10,2) NOT NULL,
    effective_from  DATE   NOT NULL,
    notes           VARCHAR(255),
    created_at      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_unit_price_history_unit FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id)
);

-- findByStorageUnitIdOrderByEffectiveFromAscIdAsc: the index gives the order too.
CREATE INDEX idx_unit_price_history_unit ON unit_price_history (storage_unit_id, effective_from, id);


-- ---------------------------------------------------------------------
-- expenses - costs, booked on a unit or general (storage_unit_id NULL)
-- ---------------------------------------------------------------------
CREATE TABLE expenses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_unit_id BIGINT,
    expense_date    DATE          NOT NULL,
    amount          NUMERIC(10,2) NOT NULL,
    description     VARCHAR(255)  NOT NULL,
    category        VARCHAR(30)   NOT NULL,
    created_at      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_expenses_unit FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id)
);

-- findAllByOrderByExpenseDateDesc, findByExpenseDateBetween and the sums over a
-- period; DESC matches the listing order, so no sort is needed.
CREATE INDEX idx_expenses_date ON expenses (expense_date DESC) INCLUDE (amount);
-- findByStorageUnitId / countByStorageUnitId / sumExpensesForUnit, and
-- sumExpensesByStorageUnit, which only looks at the rows that have a unit.
CREATE INDEX idx_expenses_unit ON expenses (storage_unit_id, expense_date)
    INCLUDE (amount) WHERE storage_unit_id IS NOT NULL;
-- findByCategory and sumExpensesByCategory[Between].
CREATE INDEX idx_expenses_category_date ON expenses (category, expense_date) INCLUDE (amount);


-- ---------------------------------------------------------------------
-- owners - the people and the comunidad de bienes that own the property
-- ---------------------------------------------------------------------
CREATE TABLE owners (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name    VARCHAR(150) NOT NULL,
    type         VARCHAR(30),
    document_id  VARCHAR(50),
    email        VARCHAR(150),
    phone        VARCHAR(50),
    bank_account VARCHAR(50),
    notes        TEXT,
    created_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_owners_full_name UNIQUE (full_name)
);

-- findByFullNameIgnoreCase, used by the seeder and by the tax filings; unique
-- because two owners differing only in case would be the same person.
CREATE UNIQUE INDEX ux_owners_full_name_lower ON owners (LOWER(full_name));
-- findByTypeOrderByFullNameAsc and findAllByOrderByFullNameAsc.
CREATE INDEX idx_owners_type_name ON owners (type, full_name);


-- ---------------------------------------------------------------------
-- ownerships - the share an owner holds in a unit
-- ---------------------------------------------------------------------
CREATE TABLE ownerships (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        BIGINT NOT NULL,
    storage_unit_id BIGINT NOT NULL,
    share_percent   NUMERIC(7,4) NOT NULL,
    notes           VARCHAR(255),
    created_at      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    -- Named as the entity declares it, so Hibernate finds it instead of adding its own.
    CONSTRAINT uk_ownership_owner_unit UNIQUE (owner_id, storage_unit_id),
    CONSTRAINT fk_ownerships_owner FOREIGN KEY (owner_id)        REFERENCES owners (id),
    CONSTRAINT fk_ownerships_unit  FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id)
);

-- findByOwnerId / countByOwnerId ride on uk_ownership_owner_unit's leading column;
-- findByStorageUnitId, countByStorageUnitId and deleteByStorageUnitId need the other side.
CREATE INDEX idx_ownerships_unit ON ownerships (storage_unit_id);


-- ---------------------------------------------------------------------
-- owner_memberships - who is part of a comunidad de bienes, and for how much
-- ---------------------------------------------------------------------
CREATE TABLE owner_memberships (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id     BIGINT NOT NULL,
    member_id     BIGINT NOT NULL,
    share_percent NUMERIC(7,4) NOT NULL,
    notes         VARCHAR(255),
    created_at    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_membership_entity_member UNIQUE (entity_id, member_id),
    CONSTRAINT fk_memberships_entity FOREIGN KEY (entity_id) REFERENCES owners (id),
    CONSTRAINT fk_memberships_member FOREIGN KEY (member_id) REFERENCES owners (id)
);

-- findByEntityId / deleteByEntityId use uk_membership_entity_member; the reverse
-- direction (findByMemberId, countByMemberId) needs its own index.
CREATE INDEX idx_owner_memberships_member ON owner_memberships (member_id);


-- ---------------------------------------------------------------------
-- tax_filings - returns already presented, with the report as it was filed
-- ---------------------------------------------------------------------
CREATE TABLE tax_filings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model       VARCHAR(20) NOT NULL,
    tax_year    INTEGER     NOT NULL,
    tax_quarter INTEGER,
    owner_id    BIGINT,
    owner_name  VARCHAR(150),
    filed_date  DATE        NOT NULL,
    amount      NUMERIC(12,2),
    description VARCHAR(255),
    snapshot    TEXT,
    notes       TEXT,
    created_at  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);
-- No FK on owner_id on purpose: a filing must survive the deletion of the owner
-- it was presented for (owner_name keeps the label).

-- findAllByOrderByYearDescQuarterDescFiledDateDescIdDesc, the only listing.
CREATE INDEX idx_tax_filings_listing
    ON tax_filings (tax_year DESC, tax_quarter DESC NULLS LAST, filed_date DESC, id DESC);
-- The seeder decides per (model, year, quarter, owner) whether a return is registered.
CREATE INDEX idx_tax_filings_key ON tax_filings (model, tax_year, tax_quarter, owner_id);


-- ---------------------------------------------------------------------
-- client_documents - ficheros archivados en la ficha de un cliente
-- (copia del DNI, contrato de trabajo, una foto...)
--
-- Aquí sólo está la ficha del documento: el contenido vive en el almacén de
-- objetos (RustFS) bajo storage_key, y se sirve por el backend.
-- ---------------------------------------------------------------------
CREATE TABLE client_documents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     BIGINT       NOT NULL REFERENCES clients (id),
    document_type VARCHAR(30)  NOT NULL,
    file_name     VARCHAR(255) NOT NULL,
    content_type  VARCHAR(120),
    size_bytes    BIGINT,
    storage_key   VARCHAR(400) NOT NULL UNIQUE,
    description   VARCHAR(255),
    uploaded_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);
-- Sin ON DELETE CASCADE a propósito: borrar un cliente pasa por la aplicación,
-- que borra antes los ficheros del almacén (ClientDocumentService.deleteByClient).
-- Un borrado directo en la base de datos debe fallar, no dejar objetos huérfanos.

-- findByClientIdOrderByUploadedAtDescIdDesc: el listado de la ficha.
CREATE INDEX idx_client_documents_client
    ON client_documents (client_id, uploaded_at DESC, id DESC);
