-- =====================================================================
-- BoxVault - PostgreSQL schema (tables, constraints and indexes)
-- =====================================================================
--
-- This file is executed automatically by the "postgres" container the first
-- time its data volume is created (docker-entrypoint-initdb.d), against the
-- database named by POSTGRES_DB. 02-seed-data.sql loads the data right after.
--
-- To install it by hand on an existing PostgreSQL server instead, create the
-- database and the role first and then run the two files against it:
--
--     CREATE ROLE boxvault LOGIN PASSWORD 'change-me';
--     CREATE DATABASE boxvault OWNER boxvault ENCODING 'UTF8' TEMPLATE template0;
--
--     psql -U boxvault -d boxvault -f 01-schema.sql
--     psql -U boxvault -d boxvault -f 02-seed-data.sql
--
-- The column names and types are the ones Hibernate maps the entities to
-- (Spring's snake_case naming strategy), so the application starts against
-- this schema without recreating anything. spring.jpa.hibernate.ddl-auto is
-- left at "update", which only ever ADDS what a new entity field needs and
-- never drops these indexes.
--
-- Money is numeric(10,2) (numeric(12,2) for the tax figures) and percentages
-- are numeric(7,4), so that 1/6 -> 16.6667 round-trips.
-- =====================================================================

-- Trigram matching for the client search (ClientRepository.searchClients uses
-- LOWER(col) LIKE '%query%', which no btree index can serve).
CREATE EXTENSION IF NOT EXISTS pg_trgm;


-- ---------------------------------------------------------------------
-- clients - tenants
-- ---------------------------------------------------------------------
CREATE TABLE clients (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name         VARCHAR(150) NOT NULL,
    email             VARCHAR(150) NOT NULL,
    phone             VARCHAR(50)  NOT NULL,
    document_id       VARCHAR(50),
    address           VARCHAR(255),
    emergency_contact VARCHAR(150),
    notes             TEXT,
    created_at        TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

-- findByEmail: exact lookup.
CREATE INDEX idx_clients_email ON clients (email);
-- The seeder and the tax reports match tenants by name; also serves ORDER BY.
CREATE INDEX idx_clients_full_name ON clients (full_name);
-- searchClients: case-insensitive substring search on the three columns.
CREATE INDEX idx_clients_full_name_trgm ON clients USING GIN (LOWER(full_name) gin_trgm_ops);
CREATE INDEX idx_clients_email_trgm     ON clients USING GIN (LOWER(email)     gin_trgm_ops);
CREATE INDEX idx_clients_phone_trgm     ON clients USING GIN (LOWER(phone)     gin_trgm_ops);


-- ---------------------------------------------------------------------
-- storage_units - trasteros, apartments and locales (a tree via parent_unit_id)
-- ---------------------------------------------------------------------
CREATE TABLE storage_units (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_number         VARCHAR(50)  NOT NULL,
    kind                VARCHAR(30),
    parent_unit_id      BIGINT,
    name                VARCHAR(100) NOT NULL,
    size_square_meters  DOUBLE PRECISION NOT NULL,
    dimensions          VARCHAR(50),
    location            VARCHAR(100),
    cadastral_reference VARCHAR(30),
    base_monthly_rate   NUMERIC(10,2) NOT NULL,
    status              VARCHAR(30)  NOT NULL,
    description         TEXT,
    created_at          TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_storage_units_unit_number UNIQUE (unit_number),
    CONSTRAINT fk_storage_units_parent FOREIGN KEY (parent_unit_id) REFERENCES storage_units (id)
);

-- findByStatus / countByStatus (dashboard occupancy).
CREATE INDEX idx_storage_units_status ON storage_units (status);
-- findByKind, findByKindAndStatus and findByKindIsNull (btree indexes NULLs too).
CREATE INDEX idx_storage_units_kind_status ON storage_units (kind, status);
-- findByParentId / countByParentId, and findByParentIsNull through the NULL entries.
CREATE INDEX idx_storage_units_parent ON storage_units (parent_unit_id);


-- ---------------------------------------------------------------------
-- rental_agreements - tenancies
-- ---------------------------------------------------------------------
CREATE TABLE rental_agreements (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agreement_number     VARCHAR(50) NOT NULL,
    storage_unit_id      BIGINT      NOT NULL,
    client_id            BIGINT      NOT NULL,
    co_client_id         BIGINT,
    start_date           DATE        NOT NULL,
    end_date             DATE,
    billing_day_of_month INTEGER     NOT NULL,
    monthly_rent         NUMERIC(10,2) NOT NULL,
    security_deposit     NUMERIC(10,2),
    deposit_paid         BOOLEAN,
    status               VARCHAR(30) NOT NULL,
    auto_renew           BOOLEAN,
    notes                TEXT,
    created_at           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_rental_agreements_number UNIQUE (agreement_number),
    CONSTRAINT fk_rental_agreements_unit      FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id),
    CONSTRAINT fk_rental_agreements_client    FOREIGN KEY (client_id)       REFERENCES clients (id),
    CONSTRAINT fk_rental_agreements_co_client FOREIGN KEY (co_client_id)    REFERENCES clients (id)
);

-- findByStorageUnitId and findByStorageUnitIdAndStatus (the current tenancy of a unit).
CREATE INDEX idx_rental_agreements_unit_status ON rental_agreements (storage_unit_id, status);
-- findByClientId / findByClientIdOrCoClientId: one index per tenant column.
CREATE INDEX idx_rental_agreements_client    ON rental_agreements (client_id);
CREATE INDEX idx_rental_agreements_co_client ON rental_agreements (co_client_id) WHERE co_client_id IS NOT NULL;
-- findAllActiveRentals / countByStatus / countDistinctActiveClients: the hot path
-- is always status = 'ACTIVE', so this index only carries those rows.
CREATE INDEX idx_rental_agreements_active ON rental_agreements (storage_unit_id, client_id)
    WHERE status = 'ACTIVE';
-- findByStatus for the other states.
CREATE INDEX idx_rental_agreements_status ON rental_agreements (status);


-- ---------------------------------------------------------------------
-- payments - one invoice per tenancy and billing month (the biggest table)
-- ---------------------------------------------------------------------
CREATE TABLE payments (
    id                    BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_agreement_id   BIGINT  NOT NULL,
    storage_unit_id       BIGINT  NOT NULL,
    client_id             BIGINT  NOT NULL,
    billing_period_month  INTEGER NOT NULL,
    billing_period_year   INTEGER NOT NULL,
    amount_due            NUMERIC(10,2) NOT NULL,
    amount_paid           NUMERIC(10,2),
    due_date              DATE    NOT NULL,
    payment_date          DATE,
    status                VARCHAR(30) NOT NULL,
    payment_method        VARCHAR(30),
    transaction_reference VARCHAR(100),
    notes                 TEXT,
    -- La factura emitida por esta mensualidad: su número de serie (correlativo
    -- por año, y por eso único), el día en que se expidió y el PDF archivado.
    -- La clave ajena se añade más abajo, cuando ya existe la tabla documents.
    invoice_number        VARCHAR(30) UNIQUE,
    invoiced_at           DATE,
    invoice_document_id   BIGINT,
    created_at            TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_agreement FOREIGN KEY (rental_agreement_id) REFERENCES rental_agreements (id),
    CONSTRAINT fk_payments_unit      FOREIGN KEY (storage_unit_id)     REFERENCES storage_units (id),
    CONSTRAINT fk_payments_client    FOREIGN KEY (client_id)           REFERENCES clients (id)
);

-- findByRentalAgreementIdAndBillingPeriodYearAndBillingPeriodMonth returns an
-- Optional: one invoice per tenancy and period. Unique, so generating the
-- invoices of a month twice can never duplicate a row; it also serves
-- findByRentalAgreementId through its leading column.
CREATE UNIQUE INDEX ux_payments_agreement_period
    ON payments (rental_agreement_id, billing_period_year, billing_period_month);

-- The revenue aggregates (month / quarter / year, paid and pending) all filter
-- by status and period and only sum the two amounts: an index-only scan.
CREATE INDEX idx_payments_status_period
    ON payments (status, billing_period_year, billing_period_month)
    INCLUDE (amount_paid, amount_due);
-- findByBillingPeriodYear[AndMonth[Between]], without a status filter.
CREATE INDEX idx_payments_period ON payments (billing_period_year, billing_period_month);
-- sumRevenueByStorageUnit / sumPaidRevenueForUnit group the paid rows by unit,
-- and the per-unit history lists every payment of a unit in period order.
CREATE INDEX idx_payments_unit_period
    ON payments (storage_unit_id, billing_period_year, billing_period_month)
    INCLUDE (status, amount_paid);
-- findByClientId.
CREATE INDEX idx_payments_client ON payments (client_id);
-- findByDueDateBetween.
CREATE INDEX idx_payments_due_date ON payments (due_date);
-- findOverduePayments / sumTotalOverdueAmount: due_date < today among the
-- unsettled rows only, which are a small fraction of a growing table.
CREATE INDEX idx_payments_pending_due_date ON payments (due_date)
    WHERE status IN ('PENDING', 'OVERDUE');


-- ---------------------------------------------------------------------
-- unit_price_history - how the monthly price of a unit evolved
-- ---------------------------------------------------------------------
CREATE TABLE unit_price_history (
    id              BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_unit_id BIGINT NOT NULL,
    monthly_price   NUMERIC(10,2) NOT NULL,
    effective_from  DATE   NOT NULL,
    notes           VARCHAR(255),
    created_at      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_unit_price_history_unit FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id)
);

-- findByStorageUnitIdOrderByEffectiveFromAscIdAsc: the index gives the order too.
CREATE INDEX idx_unit_price_history_unit ON unit_price_history (storage_unit_id, effective_from, id);


-- ---------------------------------------------------------------------
-- expenses - costs, always booked on a unit
-- ---------------------------------------------------------------------
CREATE TABLE expenses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Obligatoria: un gasto sin unidad no se puede repartir por inmueble, ni
    -- imputar en el IRPF, ni saber a quién le toca verlo (ámbito por unidades).
    storage_unit_id BIGINT        NOT NULL,
    expense_date    DATE          NOT NULL,
    amount          NUMERIC(10,2) NOT NULL,
    -- Cuota de IVA soportado incluida en amount, la que se deduce en el 303.
    -- NULL en los gastos sin IVA (el IBI) o cuando no se conoce: lo que no se
    -- declara aquí no se deduce, y cuenta entero como coste en el IRPF.
    vat_amount      NUMERIC(10,2),
    description     VARCHAR(255)  NOT NULL,
    category        VARCHAR(30)   NOT NULL,
    created_at      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_expenses_unit FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id)
);

-- findAllByOrderByExpenseDateDesc, findByExpenseDateBetween and the sums over a
-- period; DESC matches the listing order, so no sort is needed.
CREATE INDEX idx_expenses_date ON expenses (expense_date DESC) INCLUDE (amount);
-- findByStorageUnitId / countByStorageUnitId / sumExpensesForUnit, and
-- sumExpensesByStorageUnit, which only looks at the rows that have a unit.
CREATE INDEX idx_expenses_unit ON expenses (storage_unit_id, expense_date)
    INCLUDE (amount) WHERE storage_unit_id IS NOT NULL;
-- findByCategory and sumExpensesByCategory[Between].
CREATE INDEX idx_expenses_category_date ON expenses (category, expense_date) INCLUDE (amount);


-- ---------------------------------------------------------------------
-- owners - the people and the comunidad de bienes that own the property
-- ---------------------------------------------------------------------
CREATE TABLE owners (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name    VARCHAR(150) NOT NULL,
    type         VARCHAR(30),
    document_id  VARCHAR(50),
    email        VARCHAR(150),
    phone        VARCHAR(50),
    bank_account VARCHAR(50),
    notes        TEXT,
    created_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_owners_full_name UNIQUE (full_name)
);

-- findByFullNameIgnoreCase, used by the seeder and by the tax filings; unique
-- because two owners differing only in case would be the same person.
CREATE UNIQUE INDEX ux_owners_full_name_lower ON owners (LOWER(full_name));
-- findByTypeOrderByFullNameAsc and findAllByOrderByFullNameAsc.
CREATE INDEX idx_owners_type_name ON owners (type, full_name);


-- ---------------------------------------------------------------------
-- ownerships - the share an owner holds in a unit
-- ---------------------------------------------------------------------
CREATE TABLE ownerships (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id        BIGINT NOT NULL,
    storage_unit_id BIGINT NOT NULL,
    share_percent   NUMERIC(7,4) NOT NULL,
    notes           VARCHAR(255),
    created_at      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    -- Named as the entity declares it, so Hibernate finds it instead of adding its own.
    CONSTRAINT uk_ownership_owner_unit UNIQUE (owner_id, storage_unit_id),
    CONSTRAINT fk_ownerships_owner FOREIGN KEY (owner_id)        REFERENCES owners (id),
    CONSTRAINT fk_ownerships_unit  FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id)
);

-- findByOwnerId / countByOwnerId ride on uk_ownership_owner_unit's leading column;
-- findByStorageUnitId, countByStorageUnitId and deleteByStorageUnitId need the other side.
CREATE INDEX idx_ownerships_unit ON ownerships (storage_unit_id);


-- ---------------------------------------------------------------------
-- owner_memberships - who is part of a comunidad de bienes, and for how much
-- ---------------------------------------------------------------------
CREATE TABLE owner_memberships (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id     BIGINT NOT NULL,
    member_id     BIGINT NOT NULL,
    share_percent NUMERIC(7,4) NOT NULL,
    notes         VARCHAR(255),
    created_at    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_membership_entity_member UNIQUE (entity_id, member_id),
    CONSTRAINT fk_memberships_entity FOREIGN KEY (entity_id) REFERENCES owners (id),
    CONSTRAINT fk_memberships_member FOREIGN KEY (member_id) REFERENCES owners (id)
);

-- findByEntityId / deleteByEntityId use uk_membership_entity_member; the reverse
-- direction (findByMemberId, countByMemberId) needs its own index.
CREATE INDEX idx_owner_memberships_member ON owner_memberships (member_id);


-- ---------------------------------------------------------------------
-- tax_filings - returns already presented, with the report as it was filed
-- ---------------------------------------------------------------------
CREATE TABLE tax_filings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model       VARCHAR(20) NOT NULL,
    tax_year    INTEGER     NOT NULL,
    tax_quarter INTEGER,
    owner_id    BIGINT,
    owner_name  VARCHAR(150),
    filed_date  DATE        NOT NULL,
    amount      NUMERIC(12,2),
    description VARCHAR(255),
    snapshot    TEXT,
    notes       TEXT,
    -- El gasto que acredita el pago de la declaración (el cargo de la AEAT con su
    -- NRC). Sin FK, por lo mismo que owner_id: el registro tiene que sobrevivir a
    -- que se borre el gasto.
    expense_id  BIGINT,
    created_at  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);
-- No FK on owner_id on purpose: a filing must survive the deletion of the owner
-- it was presented for (owner_name keeps the label).

-- findAllByOrderByYearDescQuarterDescFiledDateDescIdDesc, the only listing.
CREATE INDEX idx_tax_filings_listing
    ON tax_filings (tax_year DESC, tax_quarter DESC NULLS LAST, filed_date DESC, id DESC);
-- The seeder decides per (model, year, quarter, owner) whether a return is registered.
CREATE INDEX idx_tax_filings_key ON tax_filings (model, tax_year, tax_quarter, owner_id);




-- ---------------------------------------------------------------------
-- documents - la ficha de un fichero archivado, sea de quien sea
--
-- Aquí sólo está el fichero: qué es, cómo se llamaba y dónde está guardado.
-- El contenido vive en el almacén de objetos (RustFS) bajo storage_key y lo
-- sirve el backend; de quién es cada documento lo dicen las tablas de relación
-- de más abajo (client_documents, rental_documents).
--
-- Se hace así, y no con una columna por dueño, para que archivar documentos de
-- algo nuevo -un gasto, un propietario- sea añadir una tabla de relación y no
-- tocar ésta ni las filas que ya existen.
-- ---------------------------------------------------------------------
-- El CHECK se declara aquí a propósito. Si no está, lo crea Hibernate con los
-- valores que el enum DocumentType tenga el día en que nazca la base, y no lo
-- vuelve a tocar nunca: cada tipo nuevo del enum funcionaría en desarrollo y
-- fallaría en el servidor al guardar. Declarado, se ve qué admite la tabla y se
-- actualiza a propósito, con su migración (ver migrations/).
CREATE TABLE documents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(30)  NOT NULL,
    file_name     VARCHAR(255) NOT NULL,
    content_type  VARCHAR(120),
    size_bytes    BIGINT,
    storage_key   VARCHAR(400) NOT NULL UNIQUE,
    description   VARCHAR(255),
    uploaded_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT documents_document_type_check CHECK (document_type IN (
        'DNI', 'CONTRATO_TRABAJO', 'NOMINA', 'FOTO',
        'CONTRATO_ALQUILER', 'ANEXO', 'FACTURA',
        'JUSTIFICANTE', 'DECLARACION', 'OTRO'))
);

-- El PDF de la factura de una mensualidad es un documento más; el cobro apunta
-- a él. Va aquí, y no en la definición de payments, porque hasta esta línea no
-- existía la tabla a la que apunta.
ALTER TABLE payments ADD CONSTRAINT fk_payments_invoice_document
    FOREIGN KEY (invoice_document_id) REFERENCES documents (id);

-- ---------------------------------------------------------------------
-- client_documents - qué documentos hay en la ficha de un cliente
-- (copia del DNI, contrato de trabajo, una foto...)
--
-- La tabla admitiría N:M, pero el UNIQUE de document_id la deja en 1:N: un
-- documento pertenece a un cliente y a uno solo. Lo que es de un alquiler
-- (la copia firmada del contrato) va en rental_documents, no aquí.
-- ---------------------------------------------------------------------
CREATE TABLE client_documents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT NOT NULL REFERENCES clients (id),
    document_id BIGINT NOT NULL REFERENCES documents (id),
    CONSTRAINT uk_client_documents_document UNIQUE (document_id)
);
-- Sin ON DELETE CASCADE a propósito, ni hacia el cliente ni hacia el documento:
-- borrar pasa por la aplicación, que borra antes los ficheros del almacén
-- (ClientDocumentService). Un borrado directo en la base de datos debe fallar,
-- no dejar objetos huérfanos en RustFS.

-- El listado de la ficha: los documentos de un cliente. El orden (por fecha de
-- subida) sale de documents, así que este índice resuelve la pertenencia y la
-- ordenación es sobre las pocas filas que quedan.
CREATE INDEX idx_client_documents_client ON client_documents (client_id);

-- ---------------------------------------------------------------------
-- rental_documents - qué documentos hay en un alquiler: la copia firmada del
-- contrato, sus anexos y las fotos de la entrega.
--
-- Cuelgan del alquiler y no del cliente a propósito: el contrato es de una
-- unidad y unas fechas concretas, y un mismo cliente puede tener varios. Mismo
-- UNIQUE que en client_documents: 1:N, un documento de un solo alquiler.
-- ---------------------------------------------------------------------
CREATE TABLE rental_documents (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_agreement_id BIGINT NOT NULL REFERENCES rental_agreements (id),
    document_id         BIGINT NOT NULL REFERENCES documents (id),
    CONSTRAINT uk_rental_documents_document UNIQUE (document_id)
);

-- El listado del contrato: los documentos de un alquiler.
CREATE INDEX idx_rental_documents_rental ON rental_documents (rental_agreement_id);

-- ---------------------------------------------------------------------
-- tax_filing_documents - qué documentos acreditan una declaración presentada:
-- el justificante con el CSV de la Sede electrónica, el PDF de la declaración
-- o el propio fichero que se importó.
--
-- Mismo UNIQUE que las anteriores: 1:N, un documento de una sola declaración.
-- ---------------------------------------------------------------------
CREATE TABLE tax_filing_documents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_filing_id BIGINT NOT NULL REFERENCES tax_filings (id),
    document_id   BIGINT NOT NULL REFERENCES documents (id),
    CONSTRAINT uk_tax_filing_documents_document UNIQUE (document_id)
);

-- El listado de la declaración: sus documentos.
CREATE INDEX idx_tax_filing_documents_filing ON tax_filing_documents (tax_filing_id);


-- ---------------------------------------------------------------------
-- roles / app_users / permisos - quién entra y qué puede hacer
--
-- Un usuario tiene un perfil (roles) que le da un nivel por área, y encima
-- puede llevar ajustes propios (user_permissions), que mandan sobre el perfil
-- en los dos sentidos: dar de más y quitar.
--
-- Hasta dónde llega es otra cosa: o full_scope (todas las unidades) o las
-- concesiones de user_unit_scopes, cada una con todo lo que cuelga de ella.
--
-- area  ∈ UNIDADES, CLIENTES, ALQUILERES, PAGOS, GASTOS, IMPUESTOS,
--         PROPIETARIOS, USUARIOS
-- level ∈ NINGUNO < LEER < ESCRIBIR < ADMINISTRAR (acumulativos)
--
-- Los perfiles de partida y el administrador inicial no se crean aquí: los crea
-- la aplicación al arrancar (SecurityBootstrap), con la contraseña de
-- BOXVAULT_ADMIN_PASSWORD y marcada para cambiarla.
-- ---------------------------------------------------------------------
CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(60) NOT NULL UNIQUE,
    description VARCHAR(255),
    system_role BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE TABLE role_permissions (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT      NOT NULL REFERENCES roles (id),
    area    VARCHAR(30) NOT NULL,
    level   VARCHAR(20) NOT NULL,
    CONSTRAINT uk_role_permissions_area UNIQUE (role_id, area)
);

CREATE TABLE app_users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             VARCHAR(60)  NOT NULL UNIQUE,
    full_name            VARCHAR(150) NOT NULL,
    email                VARCHAR(150),
    -- BCrypt con el prefijo del algoritmo: {bcrypt}$2a$...
    password_hash        VARCHAR(100) NOT NULL,
    role_id              BIGINT       NOT NULL REFERENCES roles (id),
    -- Ve todas las unidades; es lo que distingue a un gestor de quien lleva un local.
    full_scope           BOOLEAN      NOT NULL DEFAULT FALSE,
    -- Los usuarios no se borran, se dan de baja: sus rastros de auditoría siguen valiendo.
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN      NOT NULL DEFAULT FALSE,
    -- Desde cuándo valen sus tokens. Moverla echa abajo sus sesiones abiertas.
    tokens_valid_from    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at        TIMESTAMP(6),
    created_at           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

-- findByUsername: por donde entra todo el mundo (el UNIQUE ya lo indexa).

CREATE TABLE user_permissions (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT      NOT NULL REFERENCES app_users (id),
    area    VARCHAR(30) NOT NULL,
    level   VARCHAR(20) NOT NULL,
    CONSTRAINT uk_user_permissions_area UNIQUE (user_id, area)
);

-- Una concesión = esa unidad y todo su subárbol, ahora y en adelante.
CREATE TABLE user_unit_scopes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES app_users (id),
    storage_unit_id BIGINT NOT NULL REFERENCES storage_units (id),
    CONSTRAINT uk_user_unit_scopes UNIQUE (user_id, storage_unit_id)
);

-- findByUserId: las concesiones del usuario, en cada petición que filtre por ámbito.
CREATE INDEX idx_user_unit_scopes_user ON user_unit_scopes (user_id);

-- ---------------------------------------------------------------------
-- Auditoría: quién creó y quién cambió cada fila por última vez
--
-- Va aparte, en un solo sitio, porque es lo mismo en todas: el nombre del
-- usuario de la petición, que lo rellena la aplicación sola (AuditingConfig).
-- Se guarda el nombre y no el id porque los usuarios no se borran nunca -se dan
-- de baja-, así que dentro de dos años seguirá queriendo decir algo.
-- ---------------------------------------------------------------------
ALTER TABLE clients           ADD COLUMN created_by VARCHAR(60), ADD COLUMN updated_by VARCHAR(60);
ALTER TABLE storage_units     ADD COLUMN created_by VARCHAR(60), ADD COLUMN updated_by VARCHAR(60);
ALTER TABLE rental_agreements ADD COLUMN created_by VARCHAR(60), ADD COLUMN updated_by VARCHAR(60);
ALTER TABLE payments          ADD COLUMN created_by VARCHAR(60), ADD COLUMN updated_by VARCHAR(60);
ALTER TABLE expenses          ADD COLUMN created_by VARCHAR(60), ADD COLUMN updated_by VARCHAR(60);
ALTER TABLE owners            ADD COLUMN created_by VARCHAR(60), ADD COLUMN updated_by VARCHAR(60);
ALTER TABLE tax_filings       ADD COLUMN created_by VARCHAR(60), ADD COLUMN updated_by VARCHAR(60);
