-- =====================================================================
-- BoxVault - IVA soportado en los gastos y justificantes de las declaraciones
-- =====================================================================
--
-- Dos cosas, las dos aditivas:
--
-- 1. expenses.vat_amount: la cuota de IVA soportado que lleva dentro el importe
--    del gasto. Es lo que se deduce en el Modelo 303 ([28] y [29]) y lo que deja
--    de contar como coste en el IRPF, que pasa a imputar el importe sin IVA.
--    NULL = el gasto no declara IVA (el IBI) o no se sabe: se comporta como
--    antes, el importe entero es coste y no se deduce nada.
--
-- 2. tax_filing_documents: la tabla de relación que archiva en una declaración
--    presentada el justificante con el CSV de la Sede, tal como anticipaba
--    2026-09-08-documents.sql ("archivar documentos de algo nuevo será añadir
--    otra tabla de relación y nada más").
--
-- ddl-auto=update crea por su cuenta tanto la columna como la tabla, así que
-- este fichero es sólo para aplicarlo a mano si se prefiere no depender de eso
-- (o para una base creada desde 01-schema.sql anterior a este cambio):
--
--     docker compose exec -T postgres pg_dump -U boxvault -Fc boxvault > antes.dump
--     docker compose exec -T postgres psql -U boxvault -d boxvault < 2026-09-13-iva-soportado-y-justificantes.sql
--
-- No hay que parar la aplicación: no se mueve ninguna fila.
-- =====================================================================

BEGIN;

-- 1. El IVA soportado de los gastos. Sin valor por defecto a propósito: las
--    filas que ya existen quedan en NULL, que es "no declara IVA".
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS vat_amount NUMERIC(10,2);

-- 2. Los documentos de una declaración presentada.
CREATE TABLE IF NOT EXISTS tax_filing_documents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_filing_id BIGINT NOT NULL REFERENCES tax_filings (id),
    document_id   BIGINT NOT NULL REFERENCES documents (id),
    CONSTRAINT uk_tax_filing_documents_document UNIQUE (document_id)
);

-- Sin ON DELETE CASCADE, igual que client_documents y rental_documents: borrar
-- pasa por la aplicación (TaxFilingDocumentService), que borra antes el fichero
-- del almacén. Un borrado directo en la base de datos debe fallar.
CREATE INDEX IF NOT EXISTS idx_tax_filing_documents_filing ON tax_filing_documents (tax_filing_id);

COMMIT;
