-- =====================================================================
-- BoxVault - los documentos pasan a una tabla propia con tablas de relación
-- =====================================================================
--
-- Antes: client_documents llevaba a la vez la ficha del fichero (nombre, tipo,
-- clave en el almacén) y de quién era (client_id). Archivar documentos de otra
-- cosa obligaba a repetir la tabla entera o a añadirle una columna por dueño.
--
-- Ahora: documents guarda la ficha del fichero, y una tabla de relación por
-- dueño dice de quién es cada uno (client_documents, rental_documents). El
-- UNIQUE sobre document_id las deja en 1:N. Archivar documentos de algo nuevo
-- -un gasto, un propietario- será añadir otra tabla de relación y nada más.
--
-- Esto NO lo aplica solo el contenedor: 01-schema.sql únicamente se ejecuta
-- cuando el volumen de PostgreSQL se crea por primera vez, y ddl-auto=update
-- crea tablas y columnas nuevas pero no mueve filas ni borra nada. Hay que
-- lanzarlo a mano, con la aplicación parada y una copia reciente en la mano:
--
--     docker compose exec -T postgres pg_dump -U boxvault -Fc boxvault > antes.dump
--     docker compose stop boxvault
--     docker compose exec -T postgres psql -U boxvault -d boxvault < 2026-09-08-documents.sql
--     docker compose start boxvault
--
-- Los ficheros del almacén (RustFS) no se tocan: storage_key viaja tal cual, así
-- que los objetos siguen donde estaban.
-- =====================================================================

BEGIN;

-- La tabla vieja se aparta; su nombre lo va a ocupar la tabla de relación.
ALTER TABLE client_documents RENAME TO client_documents_old;
ALTER INDEX idx_client_documents_client RENAME TO idx_client_documents_old_client;

-- rental_documents con las columnas del fichero sólo existe si se llegó a
-- desplegar la versión intermedia (nunca se publicó). Si está, está vacía.
DROP TABLE IF EXISTS rental_documents;

-- ---------------------------------------------------------------------
-- Las tablas nuevas: mismas definiciones que en 01-schema.sql
-- ---------------------------------------------------------------------
CREATE TABLE documents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(30)  NOT NULL,
    file_name     VARCHAR(255) NOT NULL,
    content_type  VARCHAR(120),
    size_bytes    BIGINT,
    storage_key   VARCHAR(400) NOT NULL UNIQUE,
    description   VARCHAR(255),
    uploaded_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE client_documents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT NOT NULL REFERENCES clients (id),
    document_id BIGINT NOT NULL REFERENCES documents (id),
    CONSTRAINT uk_client_documents_document UNIQUE (document_id)
);
CREATE INDEX idx_client_documents_client ON client_documents (client_id);

CREATE TABLE rental_documents (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_agreement_id BIGINT NOT NULL REFERENCES rental_agreements (id),
    document_id         BIGINT NOT NULL REFERENCES documents (id),
    CONSTRAINT uk_rental_documents_document UNIQUE (document_id)
);
CREATE INDEX idx_rental_documents_rental ON rental_documents (rental_agreement_id);

-- ---------------------------------------------------------------------
-- Los datos: cada fila vieja es un documento y una relación con su cliente.
-- storage_key es único, así que sirve para volver a emparejarlas.
-- ---------------------------------------------------------------------
INSERT INTO documents (document_type, file_name, content_type, size_bytes, storage_key, description, uploaded_at)
SELECT document_type, file_name, content_type, size_bytes, storage_key, description, uploaded_at
FROM client_documents_old;

INSERT INTO client_documents (client_id, document_id)
SELECT old.client_id, d.id
FROM client_documents_old old
JOIN documents d ON d.storage_key = old.storage_key;

-- Red de seguridad: si algo no cuadra, la transacción entera se va abajo y la
-- tabla vieja sigue ahí.
DO $$
DECLARE
    viejas BIGINT;
    nuevas BIGINT;
BEGIN
    SELECT count(*) INTO viejas FROM client_documents_old;
    SELECT count(*) INTO nuevas FROM client_documents;
    IF viejas <> nuevas THEN
        RAISE EXCEPTION 'Migración incompleta: % documentos antes, % relaciones después', viejas, nuevas;
    END IF;
END $$;

DROP TABLE client_documents_old;

COMMIT;
