-- =====================================================================
-- V10 - un contrato lo firma quien haga falta, no un titular y un suplente
-- =====================================================================
--
-- Hasta ahora las personas de un contrato eran tres columnas: client_id,
-- co_client_id y guarantor_id. Un inquilino, un segundo titular y un fiador, y
-- se acabó. Los contratos de verdad no caben ahí: el 3D lo firman dos
-- inquilinos y un fiador, y el día que sean tres hay que tocar el esquema otra
-- vez, con su migracion, su despliegue y su reescritura de plantillas.
--
-- Esta tabla los guarda como lo que son: una lista, con el papel de cada uno y
-- el orden en que firman.
--
-- Las tres columnas de antes NO desaparecen. Pasan a ser un reflejo de la
-- lista: client_id es el primer ARRENDATARIO, co_client_id el segundo y
-- guarantor_id el primer FIADOR, y la aplicacion los mantiene al dia en cada
-- guardado. Se quedan porque de ellas cuelgan los cobros, las facturas, el
-- control de acceso por unidad y -sobre todo- el modelo 184 y el IRPF, que
-- declaran al inquilino por su NIF. Reescribir todo eso para estrenar la tabla
-- habria sido cambiar el motor y el fuselaje en el mismo vuelo.
--
-- Sin BEGIN/COMMIT: la transaccion la abre y la cierra Flyway.
-- =====================================================================

CREATE TABLE IF NOT EXISTS rental_parties (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_agreement_id BIGINT      NOT NULL,
    client_id           BIGINT      NOT NULL,
    role                VARCHAR(20) NOT NULL,
    position            INTEGER     NOT NULL DEFAULT 0,
    CONSTRAINT fk_rental_parties_agreement FOREIGN KEY (rental_agreement_id)
        REFERENCES rental_agreements (id) ON DELETE CASCADE,
    CONSTRAINT fk_rental_parties_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT rental_parties_role_check CHECK (role IN ('ARRENDATARIO', 'FIADOR')),
    -- La misma persona no firma dos veces el mismo contrato con el mismo papel.
    CONSTRAINT uk_rental_parties UNIQUE (rental_agreement_id, client_id, role)
);

-- Se lee siempre entera y en orden: las partes de un contrato.
CREATE INDEX IF NOT EXISTS idx_rental_parties_agreement
    ON rental_parties (rental_agreement_id, position);

-- ---------------------------------------------------------------------
-- Lo que ya habia, volcado a la lista
-- ---------------------------------------------------------------------
-- Idempotente por la clave unica: si esta migracion se repitiera, no duplica.
INSERT INTO rental_parties (rental_agreement_id, client_id, role, position)
SELECT r.id, r.client_id, 'ARRENDATARIO', 0
FROM rental_agreements r
WHERE r.client_id IS NOT NULL
ON CONFLICT DO NOTHING;

INSERT INTO rental_parties (rental_agreement_id, client_id, role, position)
SELECT r.id, r.co_client_id, 'ARRENDATARIO', 1
FROM rental_agreements r
WHERE r.co_client_id IS NOT NULL
ON CONFLICT DO NOTHING;

INSERT INTO rental_parties (rental_agreement_id, client_id, role, position)
SELECT r.id, r.guarantor_id, 'FIADOR', 2
FROM rental_agreements r
WHERE r.guarantor_id IS NOT NULL
ON CONFLICT DO NOTHING;
