-- =====================================================================
-- V11 - el edificio, y la comunidad de propietarios que lo administra
-- =====================================================================
--
-- Hasta ahora la casa era una sola y no hacia falta nombrarla: las seis
-- unidades raiz -los dos bajos y los cuatro pisos- colgaban del aire. Con dos
-- edificios eso deja de valer, y no solo para ordenar la pantalla: el edificio
-- es el nivel al que se concede el acceso, que es lo que permite que quien
-- administra uno no vea el otro.
--
-- El edificio NO sustituye a la unidad raiz. "Inmueble" sigue siendo BD, 3D o
-- 1E a efectos de gastos, estadisticas y filtros -eso son 121 sitios del
-- backend y 62 del frontend-; el edificio es un eje nuevo por encima. Por eso
-- building_id va solo en las raices y de las demas se deduce subiendo: guardarlo
-- en cada trastero seria repetir un dato que ya esta.
--
-- La comunidad de propietarios es cosa aparte de la comunidad de BIENES que ya
-- existe en owners. Aquella posee unidades y atribuye renta en el 184; esta no
-- posee nada ni tributa: recauda cuotas y paga los gastos del portal. Si fuera
-- un tipo mas de propietario, InvoiceIssuer la elegiria como emisora de las
-- facturas -prefiere las entidades- y acabaria encabezando contratos ajenos.
--
-- Y su libro vive fuera de expenses. Lo que la comunidad gasta no se lo deduce
-- nadie: lo deducible para un propietario es su cuota. Metidos entre los gastos,
-- el 184 y el IRPF se comerian el ascensor ADEMAS de la cuota.
--
-- Sin BEGIN/COMMIT: la transaccion la abre y la cierra Flyway.
-- =====================================================================

CREATE TABLE IF NOT EXISTS owners_communities (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(150) NOT NULL,
    tax_id     VARCHAR(30),
    iban       VARCHAR(40),
    notes      TEXT,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS buildings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(120) NOT NULL,
    address      VARCHAR(200),
    city         VARCHAR(120),
    -- Varios portales pueden compartir comunidad: eso es una mancomunidad, y su
    -- NIF y su cuenta son de ella, no de cada portal.
    community_id BIGINT,
    notes        TEXT,
    created_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_buildings_name UNIQUE (name),
    CONSTRAINT fk_buildings_community FOREIGN KEY (community_id) REFERENCES owners_communities (id)
);

-- Solo en las raices; en las demas se deduce subiendo por parent_unit_id.
ALTER TABLE storage_units ADD COLUMN IF NOT EXISTS building_id BIGINT;

-- El coeficiente de participacion de la escritura. Es de la finca registral, no
-- de quien la posee hoy: si se vende el 3D, el coeficiente se va con el piso.
-- Por eso es una columna de la unidad y no una tabla aparte: depende de la
-- unidad y de nada mas. El dia que la comunidad reparta por capitulos con reglas
-- distintas (los bajos no pagan ascensor) hara falta una tabla
-- (unidad, concepto, coeficiente), y entonces si estara ganada.
ALTER TABLE storage_units ADD COLUMN IF NOT EXISTS participation_coefficient NUMERIC(7,4);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_storage_units_building') THEN
        ALTER TABLE storage_units
            ADD CONSTRAINT fk_storage_units_building FOREIGN KEY (building_id) REFERENCES buildings (id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_storage_units_building
    ON storage_units (building_id) WHERE building_id IS NOT NULL;

-- ---------------------------------------------------------------------
-- El presupuesto y el libro
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS community_budgets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id  BIGINT       NOT NULL,
    -- "year" es palabra reservada en H2 y fragil en general.
    budget_year   INTEGER      NOT NULL,
    annual_amount NUMERIC(12,2) NOT NULL,
    notes         TEXT,
    CONSTRAINT uk_community_budgets UNIQUE (community_id, budget_year),
    CONSTRAINT fk_community_budgets_community FOREIGN KEY (community_id)
        REFERENCES owners_communities (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS community_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id    BIGINT       NOT NULL,
    entry_date      DATE         NOT NULL,
    type            VARCHAR(20)  NOT NULL,
    concept         VARCHAR(200) NOT NULL,
    amount          NUMERIC(12,2) NOT NULL,
    -- Quien paga, en cuotas y derramas; nulo en los gastos del edificio.
    storage_unit_id BIGINT,
    supplier        VARCHAR(150),
    notes           TEXT,
    created_at      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT community_entries_type_check
        CHECK (type IN ('CUOTA', 'DERRAMA', 'GASTO', 'OTRO_INGRESO', 'OTRO_GASTO')),
    CONSTRAINT fk_community_entries_community FOREIGN KEY (community_id)
        REFERENCES owners_communities (id) ON DELETE CASCADE,
    CONSTRAINT fk_community_entries_unit FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id)
);

-- El libro se lee siempre por comunidad y en orden de fecha.
CREATE INDEX IF NOT EXISTS idx_community_entries_book
    ON community_entries (community_id, entry_date DESC, id DESC);
-- Y el estado de cuentas de una unidad, por unidad.
CREATE INDEX IF NOT EXISTS idx_community_entries_unit
    ON community_entries (storage_unit_id) WHERE storage_unit_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS community_entry_documents (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_entry_id BIGINT NOT NULL,
    document_id        BIGINT NOT NULL,
    CONSTRAINT uk_community_entry_documents UNIQUE (community_entry_id, document_id),
    CONSTRAINT fk_community_entry_documents_entry FOREIGN KEY (community_entry_id)
        REFERENCES community_entries (id) ON DELETE CASCADE,
    CONSTRAINT fk_community_entry_documents_document FOREIGN KEY (document_id)
        REFERENCES documents (id)
);

-- ---------------------------------------------------------------------
-- Conceder un edificio entero a un usuario
-- ---------------------------------------------------------------------
-- Una concesion es de una unidad O de un edificio, nunca de las dos cosas ni de
-- ninguna. Conceder el edificio da sus unidades de hoy y las de manana.
ALTER TABLE user_unit_scopes ADD COLUMN IF NOT EXISTS building_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_unit_scopes_building') THEN
        ALTER TABLE user_unit_scopes
            ADD CONSTRAINT fk_user_unit_scopes_building FOREIGN KEY (building_id) REFERENCES buildings (id);
    END IF;
    -- storage_unit_id deja de ser obligatoria: ahora la concesion puede ser de
    -- un edificio.
    ALTER TABLE user_unit_scopes ALTER COLUMN storage_unit_id DROP NOT NULL;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_unit_scopes_target_check') THEN
        ALTER TABLE user_unit_scopes ADD CONSTRAINT user_unit_scopes_target_check
            CHECK ((storage_unit_id IS NOT NULL AND building_id IS NULL)
                OR (storage_unit_id IS NULL AND building_id IS NOT NULL));
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_unit_scopes_building
    ON user_unit_scopes (user_id, building_id) WHERE building_id IS NOT NULL;

-- ---------------------------------------------------------------------
-- La ficha de cliente es de un edificio
-- ---------------------------------------------------------------------
-- Una ficha pertenece al edificio que la mantiene, con su telefono, sus
-- documentos y sus notas. La misma persona puede tener ficha en dos edificios y
-- no son duplicados: en uno dio su movil y en otro el del trabajo. Quien lo ve
-- todo las agrupa por NIF; no se fusionan.
ALTER TABLE clients ADD COLUMN IF NOT EXISTS building_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clients_building') THEN
        ALTER TABLE clients
            ADD CONSTRAINT fk_clients_building FOREIGN KEY (building_id) REFERENCES buildings (id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_clients_building
    ON clients (building_id) WHERE building_id IS NOT NULL;

-- ---------------------------------------------------------------------
-- Lo que hay hoy: un edificio
-- ---------------------------------------------------------------------
-- created_at y updated_at van explicitos a proposito. El CREATE TABLE de mas
-- arriba les pone DEFAULT CURRENT_TIMESTAMP, pero en esta instalacion la tabla
-- ya existia: la creo Hibernate con ddl-auto durante las semanas en que Flyway
-- no llegaba a ejecutarse, y la creo NOT NULL y sin valor por defecto. El
-- CREATE TABLE IF NOT EXISTS no la corrige -por eso es IF NOT EXISTS- asi que
-- el INSERT tiene que traerlos puestos, y asi vale para los dos casos.
INSERT INTO buildings (name, address, city, created_at, updated_at)
SELECT 'Pasaxe 29', 'Avenida del Pasaje (A Pasaxe) 29', 'Oleiros (A Coruña)',
       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM buildings);

UPDATE storage_units
SET building_id = (SELECT id FROM buildings ORDER BY id LIMIT 1)
WHERE parent_unit_id IS NULL AND building_id IS NULL;

UPDATE clients
SET building_id = (SELECT id FROM buildings ORDER BY id LIMIT 1)
WHERE building_id IS NULL;
