-- =====================================================================
-- V15 - vencimientos anuales propios del calendario
-- =====================================================================
--
-- El calendario ya sabe los plazos de Hacienda (303, 184, IRPF), las bajas
-- avisadas y los plazos de las fianzas en el IGVS, porque salen de los datos.
-- Lo que no puede saber son las fechas que pone cada uno: el recibo del IBI del
-- ayuntamiento, la renovación del seguro, la ITV... Aquí se apuntan una vez y
-- se repiten cada año el mismo día.
--
-- Sin BEGIN/COMMIT: la transacción la abre y la cierra Flyway.
-- =====================================================================

CREATE TABLE IF NOT EXISTS calendar_reminders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(120) NOT NULL,
    -- El día del año en que vence; se repite todos los años.
    due_month    INTEGER      NOT NULL,
    due_day      INTEGER      NOT NULL,
    notes        VARCHAR(255),
    created_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    created_by   VARCHAR(60),
    updated_by   VARCHAR(60),
    CONSTRAINT calendar_reminders_month_check CHECK (due_month BETWEEN 1 AND 12),
    CONSTRAINT calendar_reminders_day_check CHECK (due_day BETWEEN 1 AND 31)
);
