-- =====================================================================
-- V18 - importar los extractos del banco y casarlos con cobros y gastos
-- =====================================================================
--
-- Cada mes había que apuntar a mano lo que ya dice el extracto del banco: quién
-- pagó qué mensualidad, qué recibos se cargaron. Ahora se sube el extracto (el
-- xls, xlsx o csv que da cada banco), la aplicación propone qué es cada
-- movimiento -el cobro de una mensualidad, un gasto, un apunte de la
-- comunidad- y una persona lo revisa antes de que se cree nada.
--
-- Cuatro tablas:
--   bank_import_profiles  cómo es el fichero de cada cuenta: en qué fila está la
--                         cabecera y qué columna es cada cosa. Los bancos no se
--                         ponen de acuerdo, y la comunidad usa otro banco.
--   bank_imports          cada extracto subido.
--   bank_import_lines     sus movimientos, con lo que se propone hacer con cada
--                         uno y, una vez aplicado, lo que se creó.
--   bank_match_rules      lo aprendido: "este concepto es este inquilino" o
--                         "este cargo es este gasto de esta unidad".
--
-- Sin BEGIN/COMMIT: la transacción la abre y la cierra Flyway.
-- =====================================================================

CREATE TABLE IF NOT EXISTS bank_import_profiles (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(120) NOT NULL,
    bank_name             VARCHAR(80),
    account_label         VARCHAR(120),
    -- PROPIETARIOS: cobros de alquiler y gastos. COMUNIDAD: el libro de la
    -- comunidad de propietarios (cuotas y gastos del edificio).
    context               VARCHAR(20)  NOT NULL,
    community_id          BIGINT,
    -- La unidad a la que van los gastos que no digan otra cosa.
    default_unit_id       BIGINT,
    -- Para los csv: con qué juego de caracteres los escribe el banco.
    encoding              VARCHAR(20)  NOT NULL DEFAULT 'UTF-8',
    -- Fila de la cabecera, empezando en 1; 0 = el fichero no tiene cabecera.
    header_row            INTEGER      NOT NULL DEFAULT 1,
    -- Las columnas, empezando en 0 (A = 0). NULL = el fichero no la tiene.
    date_column           INTEGER      NOT NULL,
    value_date_column     INTEGER,
    concept_column        INTEGER      NOT NULL,
    concept_extra_column  INTEGER,
    -- O un importe con signo, o cargo y abono por separado.
    amount_column         INTEGER,
    debit_column          INTEGER,
    credit_column         INTEGER,
    balance_column        INTEGER,
    date_format           VARCHAR(30)  NOT NULL DEFAULT 'dd/MM/yyyy',
    decimal_comma         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    created_by            VARCHAR(60),
    updated_by            VARCHAR(60),
    CONSTRAINT uk_bank_import_profiles_name UNIQUE (name),
    CONSTRAINT bank_import_profiles_context_check CHECK (context IN ('PROPIETARIOS', 'COMUNIDAD')),
    CONSTRAINT fk_bank_import_profiles_community FOREIGN KEY (community_id) REFERENCES owners_communities (id),
    CONSTRAINT fk_bank_import_profiles_unit FOREIGN KEY (default_unit_id) REFERENCES storage_units (id)
);

CREATE TABLE IF NOT EXISTS bank_imports (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id   BIGINT       NOT NULL,
    file_name    VARCHAR(255),
    status       VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    created_by   VARCHAR(60),
    CONSTRAINT bank_imports_status_check CHECK (status IN ('REVIEW', 'APPLIED')),
    CONSTRAINT fk_bank_imports_profile FOREIGN KEY (profile_id) REFERENCES bank_import_profiles (id)
);

CREATE TABLE IF NOT EXISTS bank_import_lines (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id                  BIGINT        NOT NULL,
    line_number                INTEGER       NOT NULL,
    movement_date              DATE          NOT NULL,
    value_date                 DATE,
    concept                    VARCHAR(500)  NOT NULL,
    amount                     NUMERIC(12,2) NOT NULL,
    balance                    NUMERIC(12,2),
    -- Huella del movimiento (cuenta, fecha, importe, concepto, saldo) para no
    -- importar dos veces el mismo.
    fingerprint                VARCHAR(64)   NOT NULL,
    duplicate                  BOOLEAN       NOT NULL DEFAULT FALSE,
    -- El ingreso ya estaba apuntado a mano como cobro (payment_id dice cuál):
    -- se ignora para no contarlo dos veces.
    already_recorded           BOOLEAN       NOT NULL DEFAULT FALSE,
    status                     VARCHAR(20)   NOT NULL,
    action                     VARCHAR(20)   NOT NULL,
    -- Por qué se propone lo que se propone, para que la revisión se entienda.
    reason                     VARCHAR(300),
    rental_agreement_id        BIGINT,
    period_year                INTEGER,
    period_month               INTEGER,
    expense_category           VARCHAR(30),
    storage_unit_id            BIGINT,
    community_entry_type       VARCHAR(20),
    -- Si lo asignó una persona: al aplicar se aprende como regla.
    learn                      BOOLEAN       NOT NULL DEFAULT FALSE,
    payment_id                 BIGINT,
    expense_id                 BIGINT,
    community_entry_id         BIGINT,
    error                      VARCHAR(500),
    CONSTRAINT bank_import_lines_status_check CHECK (status IN ('PENDING', 'DISCARDED', 'APPLIED', 'FAILED')),
    CONSTRAINT bank_import_lines_action_check CHECK (action IN ('RENT_PAYMENT', 'EXPENSE', 'COMMUNITY_ENTRY', 'NONE')),
    CONSTRAINT fk_bank_import_lines_import FOREIGN KEY (import_id) REFERENCES bank_imports (id) ON DELETE CASCADE,
    CONSTRAINT fk_bank_import_lines_rental FOREIGN KEY (rental_agreement_id) REFERENCES rental_agreements (id),
    CONSTRAINT fk_bank_import_lines_unit FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id)
);

CREATE INDEX IF NOT EXISTS idx_bank_import_lines_import ON bank_import_lines (import_id, line_number);
CREATE INDEX IF NOT EXISTS idx_bank_import_lines_fingerprint ON bank_import_lines (fingerprint);

CREATE TABLE IF NOT EXISTS bank_match_rules (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Las palabras que tiene que llevar el concepto, ya normalizadas.
    pattern               VARCHAR(200) NOT NULL,
    action                VARCHAR(20)  NOT NULL,
    client_id             BIGINT,
    expense_category      VARCHAR(30),
    storage_unit_id       BIGINT,
    community_entry_type  VARCHAR(20),
    created_at            TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    created_by            VARCHAR(60),
    CONSTRAINT bank_match_rules_action_check CHECK (action IN ('RENT_PAYMENT', 'EXPENSE', 'COMMUNITY_ENTRY', 'NONE')),
    CONSTRAINT fk_bank_match_rules_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE,
    CONSTRAINT fk_bank_match_rules_unit FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id) ON DELETE CASCADE
);
