-- =====================================================================
-- V20 - un cargo del banco repartido entre varias unidades
-- =====================================================================
--
-- Hay cargos que son de varias unidades a la vez: "XIAO BERNAL TERCEIROS E
-- BAIXOS", 53,40 €, es la cuota de comunidad de los dos pisos más la parte que
-- toca de los bajos. Un gasto es de una unidad -de ahí sale lo deducible de cada
-- propietario en el IRPF y en el 184-, así que el cargo se reparte: al aplicarlo
-- se crea un gasto por unidad con su parte.
--
-- El reparto se aprende como el resto: la regla guarda la proporción de cada
-- unidad, y el mes siguiente el mismo concepto sale ya repartido.
--
-- Sin BEGIN/COMMIT: la transacción la abre y la cierra Flyway.
-- =====================================================================

CREATE TABLE IF NOT EXISTS bank_import_line_splits (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id          BIGINT        NOT NULL,
    storage_unit_id  BIGINT        NOT NULL,
    -- La parte de esta unidad, en positivo; las partes suman el cargo.
    amount           NUMERIC(12,2) NOT NULL,
    position         INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT fk_bank_import_line_splits_line FOREIGN KEY (line_id) REFERENCES bank_import_lines (id) ON DELETE CASCADE,
    CONSTRAINT fk_bank_import_line_splits_unit FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id)
);

CREATE TABLE IF NOT EXISTS bank_match_rule_splits (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id          BIGINT        NOT NULL,
    storage_unit_id  BIGINT        NOT NULL,
    -- Qué parte del cargo es de esta unidad, de 0 a 1; las partes suman 1.
    share            NUMERIC(9,6)  NOT NULL,
    position         INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT fk_bank_match_rule_splits_rule FOREIGN KEY (rule_id) REFERENCES bank_match_rules (id) ON DELETE CASCADE,
    CONSTRAINT fk_bank_match_rule_splits_unit FOREIGN KEY (storage_unit_id) REFERENCES storage_units (id) ON DELETE CASCADE
);
