-- =====================================================================
-- V22 - el vocabulario con que se leen los conceptos del banco
-- =====================================================================
--
-- Las palabras que hay que conocer para leer un concepto ("trastero", "nº",
-- "xullo", "Iberdrola", "fianza"...) estaban escritas en el código, y cada
-- forma nueva de escribirlas ("Pagotrastero nmr 4") obligaba a recompilar.
-- Ahora van en esta tabla y se editan desde Banco > Vocabulario.
--
-- La tabla nace vacía: al arrancar, la aplicación rellena con los valores de
-- fábrica cada lista que no tenga ninguna palabra.
--
-- Sin BEGIN/COMMIT: la transacción la abre y la cierra Flyway.
-- =====================================================================

CREATE TABLE IF NOT EXISTS bank_vocabulary (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_key     VARCHAR(30)  NOT NULL,
    word         VARCHAR(80)  NOT NULL,
    entry_value  VARCHAR(30),
    sort_order   INTEGER      NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bank_vocabulary_list ON bank_vocabulary (list_key, sort_order);
