-- =====================================================================
-- V2 - las facturas pasan a ser datos, no sólo un PDF
-- =====================================================================
--
-- Hasta ahora una factura era un PDF que se componía leyendo el cobro en vivo.
-- Eso tiene un problema de fondo: si el cobro cambia, el mismo número imprime
-- cifras distintas, y una factura no puede funcionar así. Ahora cada factura
-- emitida es una fila con sus cifras congeladas, y el PDF se compone a partir
-- de ella.
--
-- Con eso se puede hacer lo que faltaba: RECTIFICAR. Si lo facturado deja de
-- corresponderse con la operación -cambió el importe, el inquilino, o el mes se
-- anuló- se emite una factura rectificativa, en serie aparte (R2026/0001), que
-- identifica a la rectificada y declara la causa, como exige el artículo 15 del
-- Reglamento de facturación. La rectificada no se borra ni se cambia: las filas
-- de esta tabla no se editan nunca.
--
-- Sin BEGIN/COMMIT: la transacción la abre y la cierra Flyway.
-- =====================================================================

CREATE TABLE IF NOT EXISTS invoices (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id    BIGINT       NOT NULL,
    number        VARCHAR(30)  NOT NULL,
    type          VARCHAR(20)  NOT NULL,
    -- La factura que ésta rectifica; nulo en las ordinarias.
    rectifies_id  BIGINT,
    reason        VARCHAR(255),
    issued_on     DATE         NOT NULL,
    base          NUMERIC(10,2) NOT NULL,
    vat           NUMERIC(10,2) NOT NULL,
    total         NUMERIC(10,2) NOT NULL,
    vat_rate      NUMERIC(5,2)  NOT NULL,
    -- A quién, tal como se facturó: si mañana se corrige la ficha del cliente,
    -- lo entregado sigue diciendo lo que decía.
    client_name   VARCHAR(150),
    client_tax_id VARCHAR(50),
    document_id   BIGINT,
    created_at    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_invoices_number UNIQUE (number),
    CONSTRAINT invoices_type_check CHECK (type IN ('ORDINARIA', 'RECTIFICATIVA')),
    CONSTRAINT fk_invoices_payment   FOREIGN KEY (payment_id)   REFERENCES payments (id),
    CONSTRAINT fk_invoices_rectifies FOREIGN KEY (rectifies_id) REFERENCES invoices (id),
    CONSTRAINT fk_invoices_document  FOREIGN KEY (document_id)  REFERENCES documents (id)
);

-- findByPaymentIdOrderByIssuedOnDescIdDesc: las facturas de una mensualidad.
CREATE INDEX IF NOT EXISTS idx_invoices_payment ON invoices (payment_id, issued_on DESC, id DESC);

-- El total tal como se facturó, para ver sin abrir nada que el cobro ya no
-- coincide con su factura (es lo que obliga a rectificar).
ALTER TABLE payments ADD COLUMN IF NOT EXISTS invoiced_total NUMERIC(10,2);

-- ---------------------------------------------------------------------
-- Las facturas anteriores se tiran y la serie empieza de cero
-- ---------------------------------------------------------------------
-- Esto se puede hacer HOY y no se podrá hacer nunca más. Las que había se
-- emitieron probando, salieron mal (sin el NIF del emisor, con el mes en
-- inglés) y no se entregaron a nadie: no hay ninguna factura ahí fuera con esos
-- números, así que borrarlas no deja ningún hueco real en la serie. A partir de
-- la primera que se entregue, el único camino es la rectificativa.
--
-- El orden importa: primero se suelta la referencia del cobro, luego la relación
-- con el alquiler y al final la ficha del documento, que es a quien apuntan las
-- otras dos.
--
-- Queda suelto el objeto del almacén (RustFS): el PDF en sí. SQL no llega hasta
-- ahí. Son unos kilobytes que ya no referencia nadie; se borran desde la consola
-- de RustFS si molestan.
CREATE TEMP TABLE facturas_viejas AS
SELECT d.id AS document_id, d.storage_key
FROM payments p
JOIN documents d ON d.id = p.invoice_document_id
WHERE p.invoice_number IS NOT NULL;

DO $$
DECLARE cuantas BIGINT;
BEGIN
    SELECT count(*) INTO cuantas FROM facturas_viejas;
    IF cuantas > 0 THEN
        RAISE NOTICE 'Se tiran % facturas anteriores; sus PDF quedan huérfanos en el almacén', cuantas;
    END IF;
END $$;

UPDATE payments
SET invoice_number = NULL,
    invoiced_at = NULL,
    invoiced_total = NULL,
    invoice_document_id = NULL
WHERE invoice_number IS NOT NULL;

DELETE FROM rental_documents WHERE document_id IN (SELECT document_id FROM facturas_viejas);
DELETE FROM documents        WHERE id          IN (SELECT document_id FROM facturas_viejas);

DROP TABLE facturas_viejas;
