-- =====================================================================
-- V3 - las plantillas de contrato salen del binario
-- =====================================================================
--
-- El texto del contrato venía dentro de la aplicación, en un fichero del
-- classpath: cambiar una cláusula era recompilar y desplegar. Ahora es un dato
-- más -se crea, se edita y se borra desde la pantalla de plantillas- y cada
-- contrato puede decir con cuál se compone.
--
-- El texto en sí no está aquí sino en el almacén de ficheros, como los adjuntos:
-- la base guarda de qué va cada plantilla y RustFS guarda los bytes.
--
-- La tabla nace vacía. Al arrancar, si no hay ninguna, la aplicación siembra la
-- que traía dentro y la marca por defecto, así que no hay ningún momento en el
-- que generar un contrato deje de funcionar.
-- =====================================================================

CREATE TABLE IF NOT EXISTS contract_templates (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(120) NOT NULL,
    description      VARCHAR(255),
    -- Dónde está el texto en el almacén (plantillas/uuid.txt).
    storage_key      VARCHAR(400) NOT NULL,
    size_bytes       BIGINT,
    -- La que se usa cuando el contrato no dice cuál. Sólo una a la vez.
    default_template BOOLEAN DEFAULT FALSE,
    created_at       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(60),
    updated_by       VARCHAR(60),
    CONSTRAINT uk_contract_templates_key UNIQUE (storage_key)
);

-- Una sola plantilla por defecto: lo dice el índice, no una comprobación del
-- código que un día alguien se salte desde otro sitio.
CREATE UNIQUE INDEX IF NOT EXISTS uk_contract_templates_default
    ON contract_templates (default_template) WHERE default_template;

-- Con cuál se compone el contrato de este alquiler; NULL = la de por defecto,
-- que es lo normal.
ALTER TABLE rental_agreements ADD COLUMN IF NOT EXISTS contract_template_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rental_agreements_template') THEN
        ALTER TABLE rental_agreements ADD CONSTRAINT fk_rental_agreements_template
            FOREIGN KEY (contract_template_id) REFERENCES contract_templates (id);
    END IF;
END $$;
