-- =====================================================================
-- V4 - imágenes en las plantillas de contrato
-- =====================================================================
--
-- Un contrato puede llevar el logotipo, un membrete o un sello. La imagen se
-- sube una vez y la plantilla la coloca por su NOMBRE -[[imagen:logo]]-, no por
-- su id: quien escribe una plantilla escribe palabras, no números. De ahí que el
-- nombre sea único.
--
-- Los bytes viven en el almacén de ficheros, como todo lo que pesa; aquí sólo
-- está de qué va cada una.
-- =====================================================================

CREATE TABLE IF NOT EXISTS template_images (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(60)  NOT NULL,
    storage_key  VARCHAR(400) NOT NULL,
    content_type VARCHAR(120),
    size_bytes   BIGINT,
    file_name    VARCHAR(255),
    uploaded_at  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_template_images_name UNIQUE (name),
    CONSTRAINT uk_template_images_key  UNIQUE (storage_key)
);
